### ISSUE TITLE
Code Review : TestTable

### ISSUE THREAD

**Issue by tarunlagadapati25** [tarunlagadapati25/project3#2]
Review the code, once everything is updated according to the requirements.

**Comment by MannamSaiteja** [comment]
Went through the code and it meets all the requirements.

**Comment by tarunlagadapati25** [comment]
Done for the code for reviewing it. All in proper way

**Comment by Harishankarreddy01** [comment]
I have conducted a thorough code review, meticulously ensuring that all updates align perfectly with the prescribed requirements.
