### ISSUE TITLE
Code Review : DatePicker

### ISSUE THREAD

**Issue by MannamSaiteja** [tarunlagadapati25/project3#4]
Once review code in DatePicker.js and DatePicker.css and make changes accordingly.

**Comment by SAIVENKAT818** [comment]
I have reviewed it.Every requirement is resolved.

**Comment by tarunlagadapati25** [comment]
I done for the code and all the code in DatePicker.js and DatePicker.css has resolved properly

**Comment by Krishna-coder12** [comment]
Reviewed the code and functionalities.
