### ISSUE TITLE
Develop : TestTable

### ISSUE THREAD

**Issue by SAIVENKAT818** [tarunlagadapati25/project3#5]
Modify the tabletemplate.js code according to the original table and filled in values.

**Comment by tarunlagadapati25** [comment]
I modified it and runs as it required for filled in tables.

**Comment by Harishankarreddy01** [comment]
I've refined the tabletemplate.js code to seamlessly match the original table and its data.

**Comment by Krishna-coder12** [comment]
updated the java script file to which the original values matches.
